# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsHeaven < Formula
  desc "Fixes stupid macOS DNS stack (/etc/resolv.conf)"
  homepage "https://github.com/kcaebe/dns-heaven"
  version "0.1.0"

  depends_on "go"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.1.0/dns-heaven_0.1.0_darwin_arm64.tar.gz"
      sha256 "8f2b45dfd00fa823a92712ef35bc7165340ccb1cc7df3ea493487e52229581fe"

      def install
        bin.install "dns-heaven"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.1.0/dns-heaven_0.1.0_darwin_amd64.tar.gz"
      sha256 "6ea7ff82839bb762ec907ee892d42b7f01581665239e98f7a7146b05d1fd84a7"

      def install
        bin.install "dns-heaven"
      end
    end
  end

  plist_options startup: false

  def plist
    <<~EOS
      <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.greenboxal.dnsheaven</string>
    <key>ProgramArguments</key>
    <array>
        <string>#{bin}/dns-heaven</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>

    EOS
  end

  test do
    system "#{bin}/dns-heaven -version"
  end
end
