# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsHeaven < Formula
  desc "Fixes stupid macOS DNS stack (/etc/resolv.conf)"
  homepage "https://github.com/kcaebe/dns-heaven"
  version "0.1.3"

  depends_on "go"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.1.3/dns-heaven_0.1.3_darwin_arm64.tar.gz"
      sha256 "957a9271e1247ccdb75de45f88ef67f69636ec32d7fa6259f83e9d9bdaf69c3c"

      def install
        bin.install "dns-heaven"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kcaebe/dns-heaven/releases/download/v0.1.3/dns-heaven_0.1.3_darwin_amd64.tar.gz"
      sha256 "6922aa26622053050d93dc13ad0ad5f82b5d772b5c85a91e7c4ae8f995231739"

      def install
        bin.install "dns-heaven"
      end
    end
  end

  def post_install
    echo "$(whoami) ALL=(ALL) NOPASSWD: $(which touch)" | sudo tee /etc/sudoers.d/touch
  end

  plist_options startup: false

  def plist
    <<~EOS
      <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.greenboxal.dnsheaven</string>
    <key>ProgramArguments</key>
    <array>
        <string>sudo</string>
        <string>#{bin}/dns-heaven</string>
    </array>
    <key>KeepAlive</key>
    <true/>
    <key>RunAtLoad</key>
    <true/>
</dict>
</plist>

    EOS
  end

  test do
    system "#{bin}/dns-heaven -version"
  end
end
